# Generated by Django 4.2.6 on 2023-10-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Purpose',
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'ordering': ('name',), 'verbose_name': 'purpose', 'verbose_name_plural': 'purposes'},
        ),
    ]
