# Generated by Django 4.2.6 on 2023-10-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_course_purpose_alter_purpose_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='contact',
            field=models.TextField(blank=True),
        ),
    ]
