# Generated by Django 4.2.6 on 2023-10-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collegepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='collegepart')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'collegepart',
                'verbose_name_plural': 'collegeparts',
                'ordering': ('name',),
            },
        ),
    ]
