# Generated by Django 4.2.6 on 2023-11-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_userextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='comments',
            field=models.TextField(default=-2029, max_length=300),
            preserve_default=False,
        ),
    ]
