# Generated by Django 4.2.6 on 2023-11-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_userextra_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='image',
            field=models.ImageField(unique=True, upload_to='purpose'),
        ),
    ]
