# Generated by Django 4.2.6 on 2023-11-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_userextra_comments_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='bookauthor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='booktitle',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
