# Generated by Django 4.2.6 on 2023-11-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_userorder_bookauthor_userorder_booktitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='checkedin',
            field=models.DateField(null=True),
        ),
    ]
