# Generated by Django 4.2.6 on 2023-11-09 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0013_alter_userorder_checkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purpose',
            name='available',
        ),
        migrations.RemoveField(
            model_name='purpose',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='purpose',
            name='email',
        ),
        migrations.AddField(
            model_name='purpose',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
