# Generated by Django 4.2.6 on 2023-11-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_purpose_available_remove_purpose_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purpose',
            name='image',
        ),
    ]
