# Generated by Django 4.2.6 on 2023-11-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_rename_image_collegepart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegepart',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='collegepart',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
