# Generated by Django 4.2.6 on 2023-11-10 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_userorder_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='department',
        ),
        migrations.AddField(
            model_name='userorder',
            name='depart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.department'),
        ),
    ]
