# Generated by Django 4.2.6 on 2023-11-10 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_remove_userorder_department_userorder_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.department'),
        ),
    ]
