# Generated by Django 4.2.6 on 2023-11-10 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_userorder_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='depart',
            field=models.ForeignKey(default=-2024, on_delete=django.db.models.deletion.CASCADE, to='authentication.department'),
            preserve_default=False,
        ),
    ]
