# Generated by Django 4.2.6 on 2023-11-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_userorder_depart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='depart',
        ),
        migrations.AddField(
            model_name='userorder',
            name='name',
            field=models.CharField(default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='purpose',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.purpose'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='slug',
            field=models.SlugField(default=True, max_length=20, null=True, unique=True),
        ),
    ]
