# Generated by Django 4.2.6 on 2023-11-10 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_rename_purpose_userorder_keyu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='keyu',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.department'),
        ),
    ]
