# Generated by Django 4.2.6 on 2023-11-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_alter_userorder_keyu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
