# Generated by Django 4.2.6 on 2023-11-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_alter_userorder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='available',
        ),
        migrations.AddField(
            model_name='purpose',
            name='bookauthor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='booktitle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='checkedin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='item_book',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='item_book_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='item_paper',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='item_paper_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='item_pen',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='item_pen_no',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Userorder',
        ),
    ]
