# Generated by Django 4.2.6 on 2023-11-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_remove_department_available_purpose_bookauthor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purpose',
            name='item_book',
        ),
        migrations.RemoveField(
            model_name='purpose',
            name='item_paper',
        ),
        migrations.RemoveField(
            model_name='purpose',
            name='item_pen',
        ),
    ]
