# Generated by Django 4.2.6 on 2023-11-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_remove_purpose_item_book_remove_purpose_item_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
